### ISSUE TITLE
aboult attention model

### ISSUE THREAD

**Issue by mlxu995** [chinhsuanwu/coatnet-pytorch#2]
![屏幕截图 2021-10-25 222552](https://user-images.githubusercontent.com/32296227/138714616-64d157a2-1fcf-40fe-ba22-612433ae9b3c.png)
Hi,
I noticed that the value of self.relative_bias_table is always all 0, then the following:
relative_bias = self.relative_bias_table.gather(
            0, self.relative_index.repeat(1, self.heads))
is actually meaningless (it is all 0)? 
Thanks!

**Comment by chinhsuanwu** [comment]
Hi @mlxu995 

As you can see, `self.relative_bias_table` is a `nn.Parameter` initialized with zeros that can be learned through training. So it will not be a constant value once you train it.

![img](https://user-images.githubusercontent.com/67839539/138728899-73bf2ebd-b1ad-4c3c-a863-f629123af722.png)

**Comment by mlxu995** [comment]
Thank you very much! @chinhsuanwu
