### ISSUE TITLE
About the stochastic depth

### ISSUE THREAD

**Issue by JiaquanYe** [chinhsuanwu/coatnet-pytorch#3]
Hi, I can't found the code about stochastic depth in your implementation. 

And I add the stochastic depth code and train a CoAtNet-Tiny on ImageNet 1k, but got 79.27%@top1.

Have you reproduce the results reported by the paper?

**Comment by chinhsuanwu** [comment]
Hi @JiaquanYe 

This repo is just an implementation of the architecture, and I have not trained on ImageNet. Not sure what you are referring to for "CoAtNet-Tiny", but I guess you did not follow all settings mentioned in the paper, FYI:

![img](https://user-images.githubusercontent.com/67839539/138804028-42d3a041-fc1a-4846-a129-850afcff0ee7.png)

**Comment by JiaquanYe** [comment]
> Hi @JiaquanYe
> 
> This repo is just an implementation of the architecture, and I have not trained on ImageNet. Not sure what you are referring to for "CoAtNet-Tiny", but I guess you did not follow all settings mentioned in the paper, FYI:
> 
> ![img](https://user-images.githubusercontent.com/67839539/138804028-42d3a041-fc1a-4846-a129-850afcff0ee7.png)

My mistake... I mean CoAtNet-0. I see  stochastic depth in paper and your upload your paper. 

OK, I will tune the parameter. Thanks.
