### ISSUE TITLE
About the # params

### ISSUE THREAD

**Issue by HeYDwane3** [chinhsuanwu/coatnet-pytorch#4]
Hey, I tried with your implementation, and I found the calculated #param is a little bit different from the paper, and I am curious about the reason, could you please help me out?

Take coatnet_0 for example, the calculated result is 17789624 ( 17789624 / 2^20 = 16.97), and the reported #param of the paper is 25M

Thanks in advance

**Comment by chinhsuanwu** [comment]
Hi @HeYDwane3 

Yeah, I noticed that. I'm not sure how the official implementation did it, but I did follow the instructions they gave in the paper.

Besides, the other unofficial implementation has even more problems, so we may have to wait for the official release to figure out this.
